---
- name: create host file
  hosts: all
  tasks:
         - name: copy template
           template:
                   src: host.j2
                   dest: /etc/myhosts
           when: "'dev' in group_names"
...
