---
- name: create issue file
  hosts: all
  tasks:
        - name: write development on dev hosts
          copy:
               content: "Development"
               dest: /etc/issue
          when: "'dev' in group_names"
        - name: write test on test hosts
          copy:
               content: "Test"
               dest: /etc/issue
          when: "'test' in group_names"
        - name: write production on prod hosts
          copy:
               content: "Production"
               dest: /etc/issue
          when: "'prod' in group_names"
...
