---
- name: create parttitions
  hosts: all
  tasks:
       - name: insure vg research is exist
         debug:
               msg: "volume group does not exist"
         when: "'research' not in ansible_lvm.vgs"
        
       - name: create logical volume
         block:
              - name: create 1500mb lv
                lvol:
                     vg: research
                     lv: data
                     size: 1500m
                when: "'research' in ansible_lvm.vgs"
         rescue:
              - name: if dont have 1500mb
                debug:
                      msg: "Could not create logical volume of that size"
              - name: create 800mb lv
                lvol:
                     vg: research
                     lv: data
                     size: 800m
         always:
              - name: format the lv
                filesystem:
                        fstype: ext4
                        dev: /dev/research/data
                when: "'research' in ansible_lvm.vgs"


...
