---
- name: create developers
  hosts: dev,test
  vars_files:
          - locker.yml
          - user_list.yml
  tasks:
        - name: create devops group
          group:
               name: devops
               state: present
        - name: create developer users
          user:
               name: "{{ item.name }}"
               group: devops
               state: present
               password: "{{ pw_developer | password_hash('sha512') }}"
          when: item.job == "developer"
          loop: "{{ users }}"
- name: create managers
  hosts: prod
  vars_files:
          - locker.yml
          - user_list.yml
  tasks:
        - name: create opsmgr group
          group:
               name: opsmgr
               state: present
        - name: create manager users
          user:
               name: "{{ item.name }}"
               group: opsmgr
               state: present
               password: "{{ pw_manager | password_hash('sha512') }}"
          when: item.job == "manager"
          loop: "{{ users }}"
...
