---
- name: create webcontent
  hosts: dev
  tasks:
        - name: install httpd
          yum:
              name: httpd
              state: present
        - name: start and enabled httpd
          service:
                  name: httpd
                  state: started
                  enabled: yes
        - name: start and enabled firewalld
          service:
                  name: firewalld
                  state: started
                  enabled: yes
        - name: allow http
          firewalld:
                  service: http
                  state: enabled
                  permanent: yes
                  immediate: yes
        - name: create webdev group
          group:
                  name: webdev
                  state: present
        - name: create webdev directory
          file:
               path: /webdev
               group: webdev
               mode: 2775
               setype: httpd_sys_content_t
               state: directory
        - name: create link to /var/www/html
          file: 
                src: /webdev
                dest: /var/www/html/webdev
                state: link
        - name: create content
          copy:
                content: "Devlopment"
                dest: /webdev/index.html
                setype: httpd_sys_content_t 

...
